### ISSUE TITLE
CNN Burna

### ISSUE THREAD

**Issue by Burna7** [AlessandroSaviolo/DeepLearning_0845086_HW2#3]
Just want to make it a life news

**Comment by niranjandasMM** [comment]
> Just want to make it a life news

Iam sorry, but can you explain what is the probelm you facing @Burna7

**Comment by Burna7** [comment]
> > Just want to make it a life news
> 
> Iam sorry, but can you explain what is the probelm you facing @Burna7 
> 

On how to start creating this platform it should be a for celebrate News international and local
